"""add_offline_sync_and_uuids

Revision ID: 17edbd62b834
Revises: d7b087369901
Create Date: 2026-08-15 14:29:46.488081+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17edbd62b834'
down_revision: Union[str, None] = 'd7b087369901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_operations_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_operations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_operations_operation_id'), ['operation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sync_operations_processed_at'), ['processed_at'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_device_id'), ['device_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('sync_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conflict_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('server_payload', sa.Text(), nullable=False),
    sa.Column('client_payload', sa.Text(), nullable=False),
    sa.Column('conflict_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolution_strategy', sa.String(length=50), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_conflicts_conflict_id'), ['conflict_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sync_conflicts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_conflicts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_conflicts_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_conflicts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_conflicts_status'), ['status'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_attendance_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_departments_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_employees_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_holidays_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_leaves_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaves_uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holidays_uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('sync_conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_conflicts_status'))
        batch_op.drop_index(batch_op.f('ix_sync_conflicts_id'))
        batch_op.drop_index(batch_op.f('ix_sync_conflicts_entity_type'))
        batch_op.drop_index(batch_op.f('ix_sync_conflicts_entity_id'))
        batch_op.drop_index(batch_op.f('ix_sync_conflicts_created_at'))
        batch_op.drop_index(batch_op.f('ix_sync_conflicts_conflict_id'))

    op.drop_table('sync_conflicts')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_devices_id'))
        batch_op.drop_index(batch_op.f('ix_devices_device_id'))

    op.drop_table('devices')
    with op.batch_alter_table('sync_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_operations_processed_at'))
        batch_op.drop_index(batch_op.f('ix_sync_operations_operation_id'))
        batch_op.drop_index(batch_op.f('ix_sync_operations_id'))
        batch_op.drop_index(batch_op.f('ix_sync_operations_device_id'))

    op.drop_table('sync_operations')
    # ### end Alembic commands ###
